name: "Cloud and Account Deployment"

on:
  push:
    branches:
      - main
    paths:
      - ".github/deploy/cloud_and_account/**"
      - ".github/deploy/databricks_metastore/**"
  workflow_dispatch:

jobs:
  Deploy-Databricks-Metastore:
    uses: ./.github/workflows/template-databricks-metastore-deployment.yml
    with:
      environmentName: "dev"
    secrets: inherit
  Deploy-DEV-Environment:
    needs: Deploy-Databricks-Metastore
    uses: ./.github/workflows/template-cloud-and-account-deployment.yml
    with:
      environmentName: "dev"
    secrets: inherit
  # Deploy-TEST-Environment:
  #   needs: Deploy-DEV-Environment
  #   uses: ./.github/workflows/template-cloud-and-account-deployment.yml
  #   with:
  #     environmentName: "test"
  #   secrets: inherit
  # Deploy-PROD-Environment:
  #   needs: Deploy-TEST-Environment
  #   uses: ./.github/workflows/template-cloud-and-account-deployment.yml
  #   with:
  #     environmentName: "prod"
  #   secrets: inherit
