name: 'Cloud and Account - Template'

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string

jobs:
  terraform-deployment:
    environment: ${{inputs.environmentName}}
    name: 'Cloud and Account Deployment'
    runs-on: ubuntu-latest 

    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v4
    - name: Log in to azure
      shell: pwsh
      run: |
        az login --service-principal `
          -u ${{ secrets.SPN_CLIENT_ID }} `
          -p ${{ secrets.SPN_CLIENT_SECRET }} `
          --tenant ${{ secrets.SPN_TENANT_ID }}

    - name: Setup Cloud and Account Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Cloud and Account Terraform Init
      run: terraform -chdir="./.github/deploy/cloud_and_account" init
      env:
        ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
        ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

    - name: Cloud and Account Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform -chdir="./.github/deploy/cloud_and_account" plan -input=false -var "environment=${{ inputs.environmentName }}"
      env:
        ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
        ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
    
    - name: Cloud and Account Terraform Apply
      run: terraform -chdir="./.github/deploy/cloud_and_account" apply -auto-approve -var "environment=${{ inputs.environmentName }}"
      env:
        ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
        ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}