name: Resource-Deployment

on:
  workflow_dispatch:

jobs:
  Deploy-DEV-Environment:
    uses: ./.github/workflows/cloud-and-account-template.yml
    with:
      environmentName: dev
    secrets: inherit
  # Deploy-TEST-Environment:
  #   needs: Deploy-DEV-Environment
  #   uses: ./.github/workflows/cloud-and-account-template.yml
  #   with:
  #     environmentName: test
  #   secrets: inherit
  # Deploy-PROD-Environment:
  #   needs: Deploy-TEST-Environment
  #   uses: ./.github/workflows/cloud-and-account-template.yml
  #   with:
  #     environmentName: prod
  #   secrets: inherit