name: Cloud-and-Account-PR-Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "./.github/deploy/cloud_and_account/**"
      - "./.github/workflows/cloud-and-account-template.yml"
      - "./.github/workflows/cloud-and-account-deployment.yml"
      - "./.github/workflows/cloud-and-account-pr-pipeline.yml"

jobs:
  Cloud-and-Account-Terraform-Plan-DEV:
    environment: dev
    runs-on: ubuntu-latest 

    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v4
    - name: Log in to azure
      shell: pwsh
      run: |
        az login --service-principal `
          -u ${{ secrets.SPN_CLIENT_ID }} `
          -p ${{ secrets.SPN_CLIENT_SECRET }} `
          --tenant ${{ secrets.SPN_TENANT_ID }}

    - name: Setup Cloud and Account Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Cloud and Account Terraform Init
      run: terraform -chdir="./.github/deploy/cloud_and_account" init
      env:
        ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
        ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

    - name: Cloud and Account Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform -chdir="./.github/deploy/cloud_and_account" plan -input=false -var "environment=dev"
      env:
        ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
        ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

  # LocalTest-TEST-Environment:
  #   needs: Linting
  #   uses: ./.github/workflows/unit-test-template.yml
  #   with:
  #     environmentName: test
  #   secrets: inherit

  # ClusterTest-DEV-Environment:
  #   needs: LocalTest-DEV-Environment
  #   uses: ./.github/workflows/template-test-applicaiton.yml
  #   with:
  #     environmentName: dev
  #   secrets: inherit
  # ClusterTest-TEST-Environment:
  #   needs: LocalTest-TEST-Environment
  #   uses: ./.github/workflows/template-test-applicaiton.yml
  #   with:
  #     environmentName: test
  #   secrets: inherit

