name: Cloud-and-Account-PR-Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ".github/deploy/cloud_and_account/**"
      - ".github/workflows/cloud-and-account-template.yml"
      - ".github/workflows/cloud-and-account-deployment.yml"
      - ".github/workflows/cloud-and-account-pr-pipeline.yml"
      - ".github/deploy/databricks_metastore/**"
      - ".github/workflows/databricks-metastore-template.yml"

jobs:
  Cloud-and-Account-Terraform-Plan-DEV:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v4
      - name: Log in to azure
        shell: pwsh
        run: |
          az login --service-principal `
            -u ${{ secrets.SPN_CLIENT_ID }} `
            -p ${{ secrets.SPN_CLIENT_SECRET }} `
            --tenant ${{ secrets.SPN_TENANT_ID }}

      - name: Setup Cloud and Account Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Databricks Metastore Terraform Init
        run: |
          cd ./.github/deploy/databricks_metastore
          terraform init
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

      - name: Databricks Metastore Terraform Format
        run: terraform fmt -check

      - name: Databricks Metastore Terraform Plan
        run: |
          cd ./.github/deploy/databricks_metastore
          terraform plan -input=false
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

      - name: Cloud and Account Terraform Init
        run: |
          cd ./.github/deploy/could_and_account
          terraform init -backend-config="key=dev_terraform_could_and_account.tfstate"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

      - name: Cloud and Account Terraform Format
        run: terraform fmt -check

      - name: Cloud and Account Terraform Plan
        run: |
          cd ./.github/deploy/could_and_account
          terraform plan -input=false -var "environment=dev"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

  Cloud-and-Account-Terraform-Plan-Test:
    environment: test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v4
      - name: Log in to azure
        shell: pwsh
        run: |
          az login --service-principal `
            -u ${{ secrets.SPN_CLIENT_ID }} `
            -p ${{ secrets.SPN_CLIENT_SECRET }} `
            --tenant ${{ secrets.SPN_TENANT_ID }}

      - name: Setup Cloud and Account Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Cloud and Account Terraform Init
        run: |
          cd ./.github/deploy/could_and_account
          terraform init -backend-config="key=test_terraform_could_and_account.tfstate"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

      - name: Cloud and Account Terraform Format
        run: terraform fmt -check

      - name: Cloud and Account Terraform Plan
        run: |
          cd ./.github/deploy/could_and_account
          terraform plan -input=false -var "environment=test"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
