name: "Cloud and Account Deployment"

on:
  push:
    branches:
      - main
    paths:
      - ".github/deploy/cloud_and_account/**"
      - ".github/deploy/databricks_metastore/**"
  workflow_dispatch:

jobs:
  Deploy-Databricks-Metastore:
    uses: ./.github/workflows/databricks-metastore-template.yml
    secrets: inherit
  Deploy-DEV-Environment:
    uses: ./.github/workflows/cloud-and-account-template.yml
    with:
      environmentName: dev
    secrets: inherit
  Deploy-TEST-Environment:
    uses: ./.github/workflows/cloud-and-account-template.yml
    with:
      environmentName: test
    secrets: inherit
  # Deploy-PROD-Environment:
  #   uses: ./.github/workflows/cloud-and-account-template.yml
  #   with:
  #     environmentName: prod
  #   secrets: inherit
