name: Databricks Workspace Deployment

on:
  push:
    branches:
      - main
    paths:
      - ".github/deploy/databricks_workspace/**"
      - "src/**"
      - "tests/**"
      - "workspace/**"
      - ".github/deploy/application/**"
      - "requirements-deploy.txt"
      - "requirements.txt"
      - "setup.cfg"
      - "setup.py"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  Deploy-Databricks-Workspace-DEV-Environment:
    uses: ./.github/workflows/template-databricks-workspace-deployment.yml
    with:
      environmentName: dev
      buildId: "${{github.run_id}}"
    secrets: inherit
  Deploy-Databricks-Workspace-TEST-Environment:
    needs: Deploy-Databricks-Workspace-DEV-Environment
    uses: ./.github/workflows/template-databricks-workspace-deployment.yml
    with:
      environmentName: test
      buildId: "${{github.run_id}}"
    secrets: inherit
  # Deploy-Databricks-Workspace-PROD:
  #   needs: Deploy-Databricks-Workspace-TEST-Environment
  #   uses: ./.github/workflows/template-databricks-workspace-deployment.yml
  #   with:
  #     environmentName: prod
  #     buildId: ""
  #   secrets: inherit
