name: Databricks Workspace Deployment

on:
  push:
    branches:
      - main
    paths:
      - ".github/deploy/databricks_workspace/**"
      - "src/**"
      - ".github/deploy/application/**"
  
  workflow_dispatch:

jobs:
  Deploy-DEV-Application:
    uses: ./.github/workflows/databricks-workspace-template.yml
    with:
      environmentName: dev
    secrets: inherit
  # Deploy-TEST-Application:
  #   needs: Deploy-DEV-Application
  #   uses: ./.github/workflows/databricks-workspace-template.yml
  #   with:
  #     environmentName: test
  #   secrets: inherit
  # Deploy-PROD-Application:
  #   needs: Deploy-TEST-Application
  #   uses: ./.github/workflows/databricks-workspace-template.yml
  #   with:
  #     environmentName: prod
  #   secrets: inherit
