
name: Databricks Workspace - Template

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
jobs:
  deploy_environment:
    environment: ${{ inputs.environmentName }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Log in to azure
        shell: pwsh
        run: |
          az login --service-principal `
          -u ${{ secrets.SPN_CLIENT_ID }} `
          -p ${{ secrets.SPN_CLIENT_SECRET }} `
          --tenant ${{ secrets.SPN_TENANT_ID }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Build Spetlr Wheel
        shell: pwsh
        run: .github/deploy/application/build.ps1 `
            -environmentName "${{ inputs.environmentName }}"
            -buildId "${{ github.run_id }}"
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
  
      - name: Workspace Terraform Init
        run: terraform -chdir="./.github/deploy/databricks_workspace" init
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
  
      - name: Workspace Terraform Format
        run: terraform fmt -check
  
      - name: Terraform Plan
        run: terraform -chdir="./.github/deploy/databricks_workspace" plan -input=false -var "environment=${{ inputs.environmentName }}"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
      
      - name: Workspace Terraform Apply
        run: terraform -chdir="./.github/deploy/databricks_workspace" apply -auto-approve -var "environment=${{ inputs.environmentName }}"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

      - name: Azure logout
        shell: pwsh
        run: az logout

