name: Databricks-Workspace-PR-Pipeline

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "./.github/deploy/cloud_and_account/**"
      - "./.github/workflows/cloud-and-account-template.yml"
      - "./.github/workflows/cloud-and-account-deployment.yml"
      - "./img/**"
      - "./README.md"

jobs:
  Workspace-Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
      - name: Black
        shell: pwsh
        run: black --check .
      - name: iSort
        shell: pwsh
        run: isort --check .
      - name: Flake8
        shell: pwsh
        run: flake8 .

  Workspace-LocalTest-DEV-Environment:
    needs: Workspace-Linting
    uses: ./.github/workflows/unit-test-template.yml
    with:
      environmentName: dev
    secrets: inherit

  Workspace-DEV-Terraform-Plan:
    needs: Workspace-LocalTest-DEV-Environment
    environment: ${{inputs.environmentName}}
    name: 'Workspace-DEV-Terraform-Plan'
    runs-on: ubuntu-latest 

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v4
      - name: Log in to azure
        shell: pwsh
        run: |
          az login --service-principal `
            -u ${{ secrets.SPN_CLIENT_ID }} `
            -p ${{ secrets.SPN_CLIENT_SECRET }} `
            --tenant ${{ secrets.SPN_TENANT_ID }}

      - name: Workspace Terraform Init
        run: terraform -chdir="./.github/deploy/databricks_workspace" init
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

      - name: Workspace Terraform Format
        run: terraform fmt -check

      - name: Workspace Terraform Plan
        run: terraform -chdir="./.github/deploy/databricks_workspace" plan -input=false -var "environment=${{ inputs.environmentName }}"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

  # LocalTest-TEST-Environment:
  #   needs: Linting
  #   uses: ./.github/workflows/unit-test-template.yml
  #   with:
  #     environmentName: test
  #   secrets: inherit

  # ClusterTest-DEV-Environment:
  #   needs: LocalTest-DEV-Environment
  #   uses: ./.github/workflows/template-test-applicaiton.yml
  #   with:
  #     environmentName: dev
  #   secrets: inherit
  # ClusterTest-TEST-Environment:
  #   needs: LocalTest-TEST-Environment
  #   uses: ./.github/workflows/template-test-applicaiton.yml
  #   with:
  #     environmentName: test
  #   secrets: inherit

