name: Databricks Workspace Deployment

on:
  push:
    branches:
      - main
    paths:
      - ".github/deploy/databricks_workspace/**"
      - "src/**"
      - ".github/deploy/application/**"
      - "requirements-deploy.txt"
      - "requirements.txt"
      - "setup.cfg"
      - "setup.py"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  Deploy-Databricks-Workspace-DEV:
    uses: ./.github/workflows/databricks-workspace-template.yml
    with:
      environmentName: dev
    secrets: inherit
  Deploy-Databricks-Workspace-TEST:
    needs: Deploy-Databricks-Workspace-DEV
    uses: ./.github/workflows/databricks-workspace-template.yml
    with:
      environmentName: test
    secrets: inherit
  # Deploy-Databricks-Workspace-PROD:
  #   needs: Deploy-Databricks-Workspace-TEST
  #   uses: ./.github/workflows/databricks-workspace-template.yml
  #   with:
  #     environmentName: prod
  #   secrets: inherit
