name: Databricks-Workspace-PR-Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - ".github/deploy/cloud_and_account/**"
      - ".github/workflows/template-cloud-and-account-deployment.yml"
      - ".github/workflows/cloud-and-account-deployment.yml"
      - ".github/workflows/template-cloud-and-account-pr-pipeline.yml"
      - ".github/workflows/cloud-and-account-pr-pipeline.yml"
      - ".github/deploy/databricks_metastore/**"
      - ".github/workflows/template-databricks-metastore-deployment.yml"
      - "img/**"
      - "README.md"

jobs:
  Workspace-Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
      - name: Black
        shell: pwsh
        run: black --check .
      - name: iSort
        shell: pwsh
        run: isort --skip=workspace/* .
      - name: Flake8
        shell: pwsh
        run: flake8 --exclude=workspace .

  Workspace-LocalTest-DEV-Environment:
    needs: Workspace-Linting
    uses: ./.github/workflows/template-spetlr-unit-test.yml
    with:
      environmentName: "dev"
      buildId: "${{github.run_id}}"
    secrets: inherit

  Workspace-ClusterTest-DEV-Environment:
    needs: Workspace-LocalTest-DEV-Environment
    uses: ./.github/workflows/template-spetlr-cluster-test.yml
    with:
      environmentName: "dev"
      buildId: "${{github.run_id}}"
    secrets: inherit

  Workspace-Terraform-Plan-DEV-Environment:
    needs: Workspace-LocalTest-DEV-Environment
    uses: ./.github/workflows/template-workspace-terraform-plan.yml
    with:
      environmentName: "dev"
      buildId: "${{github.run_id}}"
    secrets: inherit

  Workspace-LocalTest-TEST-Environment:
    needs: Workspace-Linting
    uses: ./.github/workflows/template-spetlr-unit-test.yml
    with:
      environmentName: "test"
      buildId: "${{github.run_id}}"
    secrets: inherit

  Workspace-ClusterTest-TEST-Environment:
    needs: Workspace-LocalTest-TEST-Environment
    uses: ./.github/workflows/template-spetlr-cluster-test.yml
    with:
      environmentName: "test"
      buildId: "${{github.run_id}}"
    secrets: inherit

  Workspace-Terraform-Plan-TEST-Environment:
    needs: Workspace-LocalTest-TEST-Environment
    uses: ./.github/workflows/template-workspace-terraform-plan.yml
    with:
      environmentName: "test"
      buildId: "${{github.run_id}}"
    secrets: inherit
