name: Databricks-MLOps-PR-Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ".github/deploy/databricks_mlops/**"
      - ".github/workflows/template-databricks-mlops-deployment.yml"
      - ".github/workflows/databricks-mlops-deployment.yml"
      - "mlops_notebooks/**"

jobs:
  Databricks-MLOps-Plan-DEV:
    environment: "dev"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to azure
        shell: pwsh
        run: |
          az login --service-principal `
            -u ${{ secrets.SPN_CLIENT_ID }} `
            -p ${{ secrets.SPN_CLIENT_SECRET }} `
            --tenant ${{ secrets.SPN_TENANT_ID }}

      - name: Setup Cloud and Account Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Cloud and Account Terraform Init
        run: terraform -chdir="./.github/deploy/databricks_mlops" init -backend-config="key=dev_terraform_databricks_mlops.tfstate"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
          TF_VAR_db_account_id: ${{ secrets.SPN_DATABRICKS_ACCOUNT_ID }}

      - name: Cloud and Account Terraform Format
        run: terraform fmt -check

      - name: Cloud and Account Terraform Plan
        run: terraform -chdir="./.github/deploy/databricks_mlops" init -backend-config="key=dev_terraform_databricks_mlops.tfstate"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
          TF_VAR_db_account_id: ${{ secrets.SPN_DATABRICKS_ACCOUNT_ID }}