
name: Deployment-Application - Template

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
jobs:
  deploy_environment:
    environment: azure-${{ inputs.environmentName }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Log in to azure
        shell: pwsh
        run: |
          az login --service-principal `
            -u ${{ secrets.SPN_CLIENT_ID }} `
            -p ${{ secrets.SPN_CLIENT_SECRET }} `
            --tenant ${{ secrets.SPN_TENANT_ID }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Deploy Application
        shell: pwsh
        run: .github/application/deploy.ps1 `
            -environmentName "${{ inputs.environmentName }}"

      - name: Azure logout
        shell: pwsh
        run: az logout

