name: Test-Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
      - name: Black
        shell: pwsh
        run: black --check .
      - name: iSort
        shell: pwsh
        run: isort --check .
      - name: Flake8
        shell: pwsh
        run: flake8 .

  LocalTest-DEV-Environment:
    needs: Linting
    uses: ./.github/workflows/unittest_template.yml
    with:
      environmentName: dev
    secrets: inherit

  # LocalTest-TEST-Environment:
  #   needs: Linting
  #   uses: ./.github/workflows/unittest_template.yml
  #   with:
  #     environmentName: test
  #   secrets: inherit

  # ClusterTest-DEV-Environment:
  #   needs: LocalTest-DEV-Environment
  #   uses: ./.github/workflows/template-test-applicaiton.yml
  #   with:
  #     environmentName: dev
  #   secrets: inherit
  # ClusterTest-TEST-Environment:
  #   needs: LocalTest-TEST-Environment
  #   uses: ./.github/workflows/template-test-applicaiton.yml
  #   with:
  #     environmentName: test
  #   secrets: inherit

