name: Cluster Test - Template

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
      buildId:
        required: true
        type: string
jobs:
  Run-Cluster-Test:
    environment: ${{ inputs.environmentName }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to azure
        shell: pwsh
        run: |
          az login --service-principal `
            -u ${{ secrets.SPN_CLIENT_ID }} `
            -p ${{ secrets.SPN_CLIENT_SECRET }} `
            --tenant ${{ secrets.SPN_TENANT_ID }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup Databricks CLI
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks -v

      - name: Connect to Databricks
        shell: pwsh
        run: |
          .github/deploy/application/connect_DB_api.ps1 `
            -environmentName "${{ inputs.environmentName }}" `
            -tenantId ${{ secrets.SPN_TENANT_ID }} `
            -clientId ${{ secrets.SPN_CLIENT_ID }} `
            -clientSecret ${{ secrets.SPN_CLIENT_SECRET }}

      - name: Cluster Test job (integration testing)
        shell: pwsh
        run: |
          .github/deploy/application/test.ps1 `
            -environmentName "${{ inputs.environmentName }}" `
            -buildId "${{ inputs.buildId }}"

      - name: Azure logout
        shell: pwsh
        run: az logout
