name: "Metastore - PR Template"

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string

jobs:
  Cloud-and-Account-Terraform-Plan:
    environment: ${{inputs.environmentName}}
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v4
      - name: Log in to azure
        shell: pwsh
        run: |
          az login --service-principal `
            -u ${{ secrets.SPN_CLIENT_ID }} `
            -p ${{ secrets.SPN_CLIENT_SECRET }} `
            --tenant ${{ secrets.SPN_TENANT_ID }}

      - name: Setup Cloud and Account Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Databricks Metastore Terraform Init
        run: terraform -chdir="./.github/deploy/databricks_metastore" init
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
          TF_VAR_db_account_id: ${{ secrets.SPN_DATABRICKS_ACCOUNT_ID }}

      - name: Databricks Metastore Terraform Format
        run: terraform fmt -check

      - name: Databricks Metastore Terraform Plan
        run: terraform -chdir="./.github/deploy/databricks_metastore" plan -input=false
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
          TF_VAR_db_account_id: ${{ secrets.SPN_DATABRICKS_ACCOUNT_ID }}
