name: Local Test (Unittest) - Template

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
      buildId:
        required: true
        type: string

jobs:
  Workspace-Terraform-Plan:
    environment: ${{ inputs.environmentName }}
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v4
      - name: Log in to azure
        shell: pwsh
        run: |
          az login --service-principal `
            -u ${{ secrets.SPN_CLIENT_ID }} `
            -p ${{ secrets.SPN_CLIENT_SECRET }} `
            --tenant ${{ secrets.SPN_TENANT_ID }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build Spetlr Wheel
        shell: pwsh
        run: |
          .github/deploy/application/build.ps1 `
            -environmentName "${{ inputs.environmentName }}" `
            -buildId "${{ inputs.buildId }}"

      - name: Setup Workspace Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Workspace Terraform Init
        run: terraform -chdir="./.github/deploy/databricks_workspace" init -backend-config="key=${{ inputs.environmentName }}_terraform_datarbricks_workspace.tfstate"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}

      - name: Workspace Terraform Format
        run: terraform fmt -check

      - name: Workspace Terraform Plan
        run: terraform -chdir="./.github/deploy/databricks_workspace" plan -input=false -var "environment=${{ inputs.environmentName }}"
        env:
          ARM_ACCESS_KEY: ${{ secrets.SPN_STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
