name: 'Deploy resources with Terraform Template'

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}

jobs:
  deploy_environment:
    environment: ${{ inputs.environmentName }}
    name: 'Resources Deployment with Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt -check

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -var "environment = ${{ inputs.environmentName }}"