name: 'Resources-Deployment Template'

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string

jobs:
  terraform-deployment:
    environment: ${{inputs.environmentName}}
    name: 'Terraform Plan'
    runs-on: ubuntu-latest 

    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v4
    - name: Log in to azure
      shell: pwsh
      run: |
        az login --service-principal `
          -u ${{ secrets.SPN_CLIENT_ID }} `
          -p ${{ secrets.SPN_CLIENT_SECRET }} `
          --tenant ${{ secrets.SPN_TENANT_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform -chdir="./.github/terraform" init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform -chdir="./.github/terraform" plan -input=false
    
    - name: Terraform Apply
      run: terraform -chdir="./.github/terraform" apply -auto-approve tfplan -var "environment=${{ inputs.environmentName }}"